export const GET_PETS = 'GET_PETS';
export const GET_PETS_SUCCESS = 'GET_PETS_SUCCESS';

export const UPDATE_PET = 'UPDATE_PET';
export const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';

export const GET_PET_ACTIVITIES = 'GET_PET_ACTIVITIES';
export const GET_PET_ACTIVITIES_SUCCESS = 'GET_PET_ACTIVITIES_SUCCESS';

export const CREATE_PET_ACTIVITY = 'CREATE_PET_ACTIVITY';
export const CREATE_PET_ACTIVITY_SUCCESS = 'CREATE_PET_ACTIVITY_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_LOGIN_STATUS = 'GET_LOGIN_STATUS';
export const GET_LOGIN_STATUS_SUCCESS = 'GET_LOGIN_STATUS_SUCCESS';
