export const GET_PETS = 'GET_PETS';
export const GET_PETS_SUCCESS = 'GET_PETS_SUCCESS';

export const GET_PET_ACTIVITIES = 'GET_PET_ACTIVITIES';
export const GET_PET_ACTIVITIES_SUCCESS = 'GET_PET_ACTIVITIES_SUCCESS';
